package com.ligadata.jpmml.concrete

import com.ligadata.jpmml.deployment.{JpmmlModelManagerMapImpl, JpmmlModelManagerFileReader}
import com.ligadata.jpmml.evaluation.JpmmlEvaluator

trait JpmmlModelEvaluatorWired extends JpmmlModelManagerFileReader with JpmmlEvaluator with JpmmlModelManagerMapImpl