#!/bin/bash
# A sample script  I used to test the engine. Yet to implement fat jars and packaging the external dependencies

cd $FATAFATLIBPATH

export JSON_JARS=$HOME/.ivy2/cache/org.json4s/json4s-jackson_2.10/jars/json4s-jackson_2.10-3.2.9.jar:$HOME/.ivy2/cache/org.json4s/json4s-ast_2.10/jars/json4s-ast_2.10-3.2.5.jar:$HOME/.ivy2/cache/org.json4s/json4s-ast_2.10/jars/json4s-ast_2.10-3.2.9.jar:$HOME/.ivy2/cache/org.json4s/json4s-native_2.10/jars/json4s-native_2.10-3.2.9.jar:$HOME/.ivy2/cache/org.json4s/json4s-native_2.10/jars/json4s-native_2.10-3.2.5.jar:$HOME/.ivy2/cache/org.json4s/json4s-ast_2.11/jars/json4s-ast_2.11-3.2.10.jar:$HOME/.ivy2/cache/org.json4s/json4s-core_2.10/jars/json4s-core_2.10-3.2.9.jar:$HOME/.ivy2/cache/org.json4s/json4s-core_2.10/jars/json4s-core_2.10-3.2.5.jar:$HOME/.ivy2/cache/org.json4s/json4s-core_2.11/jars/json4s-core_2.11-3.2.10.jar:$HOME/.ivy2/cache/org.json4s/json4s-jackson_2.11/jars/json4s-jackson_2.11-3.2.10.jar

export JACKSON_JARS=$HOME/.ivy2/cache/com.fasterxml.jackson.core/jackson-core/bundles/jackson-core-2.3.1.jar:$HOME/.ivy2/cache/com.fasterxml.jackson.core/jackson-annotations/bundles/jackson-annotations-2.3.0.jar:$HOME/.ivy2/cache/com.fasterxml.jackson.core/jackson-databind/bundles/jackson-databind-2.3.1.jar:$HOME/.ivy2/cache/com.thoughtworks.paranamer/paranamer/jars/paranamer-2.6.jar:$HOME/.ivy2/cache/com.thoughtworks.paranamer/paranamer/jars/paranamer-2.1.jar:$HOME/.ivy2/cache/com.thoughtworks.paranamer/paranamer/jars/paranamer-2.3.jar:$HOME/.ivy2/cache/com.thoughtworks.paranamer/paranamer/jars/paranamer-2.5.6.jar:$HOME/.ivy2/cache/com.thoughtworks.paranamer/paranamer/jars/paranamer-2.4.1.jar

export MAPDB_JARS=$HOME/.ivy2/cache/org.mapdb/mapdb/bundles/mapdb-1.0.6.jar:$HOME/.ivy2/cache/org.mapdb/mapdb/jars/mapdb-0.9.0.jar

export JODA_JARS=$HOME/.ivy2/cache/org.joda/joda-convert/jars/joda-convert-1.6.jar:$HOME/my_libs/joda-time-2.4.jar

export fatafat_classpath=$FATAFATLIBPATH/log4j-1.2.17.jar:$FATAFATLIBPATH/msgsandcontainers_2.10-1.0.jar:$FATAFATLIBPATH/metadata_2.10-1.0.jar:$FATAFATLIBPATH/fatafatbase_2.10-1.0.jar:$FATAFATLIBPATH/basetypes_2.10-0.1.0.jar:$FATAFATLIBPATH/metadataapi_2.10-1.0.jar:$FATAFATLIBPATH/storage_2.10-0.0.0.2.jar:$FATAFATLIBPATH/pmmlruntime_2.10-1.0.jar:$FATAFATLIBPATH/pmmludfs_2.10-1.0.jar:$JODA_JARS:$JSON_JARS:$MAPDB_JARS:$JACKSON_JARS
echo $fatafat_classpath
scala  -J-Xmx1024M -cp $fatafat_classpath $FATAFATLIBPATH/fatafatmanager_2.10-1.0.jar --config $FATAFATLIBPATH/simp_samp_node1_config.cfg
